apiVersion: v1
kind: Service
metadata:
  name: gin-blog-upload-svc
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: gin-blog-upload
  ports:
    - name: http
      port: 9091
      targetPort: 9091
